// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://wskwblytqmyjqcgsxeky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indza3dibHl0cW15anFjZ3N4ZWt5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIyMDQzNDUsImV4cCI6MjA4Nzc4MDM0NX0.JjDDkfWo0jFOBeCWECLmKMZUjiMZR7ZGvAyZI3qemA4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);